project:
  type: book

book:
  title: 'Amfiteatres romans'
  author:
    - name: 'Miquel Vàzquez-Santiago'
      orcid: '0000-0002-9432-4297'
      email: 'vazquez.miquel@gmail.com' 
      github: 'mvazquezs' 
  date: today
  date-format: 'MMMM DD, YYYY'
  chapters:
    - index.qmd
    - 01_abstract.qmd
    - 02_introduccio.qmd
    - 03_material_methods.qmd
    - 04_resultats.qmd
    - 05_conclusions.qmd
    - references.bib  


bibliography: references.bib

format:
  html:
    theme:
      light: united
    css: styles-tango.css
    code-fold: true
    code-summary: 'Hidden code'
  
  # pdf:
  #   documentclass: scrreprt

editor: visual