project:
  type: book
  output-dir: _book

book:
  title: "Anàlisi Quantitativa d'Amfiteatres Romans"
  author:
    - name: 'Miquel Vàzquez-Santiago'
      orcid: '0000-0002-9432-4297'
      email: 'vazquez.miquel@gmail.com' 
      github: 'mvazquezs' 
  date: today
  date-format: 'MMMM DD, YYYY'
  chapters:
    - index.qmd
    - 01_abstract.qmd
    - 02_introduccio.qmd
    - 03_material_methods.qmd
    - 04_resultats.qmd
    - 05_conclusions.qmd
    - 06_references.qmd
  appendices:
    - statistical_analysis_plan.qmd


bibliography: references.bib

format:
  html:
    theme: united
    highlight-style: tango
    css: styles.css
    code-fold: true
    code-summary: 'Hidden code'
  
  pdf:
    documentclass: scrreprt
    mainfont: "LMRoman10-Regular"
    fontsize: 12pt

editor: visual